theme: jekyll-theme-minimal
title: Madhumitha's homepage
description: A humble blog documenting my path learning technology step-by-step.

# Author info
author:
  name: "DevInShadow"
  bio: "Beginner coder sharing honest lessons and progress."
  location: "Bengaluru, Karnataka"
